### PR TITLE
Add LESS support

### PR DESCRIPTION
**Pull request by sparanoid**

### CODE REVIEW

**Comment by sunng87** [comment]
Also it's better to have a less variable `@FontAwesomePath` just like font-awesome.

**Comment by lexrus** [comment]
@sparanoid Merged. Thank you.
@sunng87 Definitely. Thank you. https://github.com/lexrus/fontdiao/commit/d4300a3208486313712f0493dd3bf2e94ffd8641

**Comment by sunng87** [comment]
@lexrus Could you please tag new a release :-)

**Comment by lexrus** [comment]
@sunng87 Done.
https://github.com/lexrus/fontdiao/tree/0.0.6

**Pull request merged**
